version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker/php/90-xdebug.ini:/usr/local/etc/php/conf.d/90-xdebug.ini
    env_file: .env
    networks:
      - estudo

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - estudo

networks:
  estudo:
    driver: bridge